version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'app'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./app:/root/app
    command: sh -c "cd app && python demo-bot.py"
